version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
